[test]
levels = ["syntax", "coverage", "install", "registration", "instantiation", "execution-light"]
publish = true

[test.workflows]
cpu =  'all'
gpu = []

[test.platforms]
linux = true
macos = true
windows = true
windows_portable = true
linux_gpu = false
windows_gpu = false
windows_portable_gpu = false
macos_desktop = true
windows_desktop = true
windows_desktop_gpu = false
