[project]
name = "comfyui-cadabra"
description = "Warning, uses experimental package `comfy-env` to attempt a one click isolated install. Will download and use pixi package manager. CAD file processing nodes for ComfyUI with interactive 3D OCC CAD viewer. Load STEP, IGES, BREP files and generate meshes using OCC, GMSH."
version = "1.1.1"
license = {file = "LICENSE"}

[project.urls]
Repository = "https://github.com/PozzettiAndrea/ComfyUI-CADabra"
Documentation = "https://github.com/PozzettiAndrea/ComfyUI-CADabra#readme"

[tool.comfy]
PublisherId = "pznodes"
DisplayName = "CADabra"
web = "javascript"
Icon = "https://raw.githubusercontent.com/PozzettiAndrea/ComfyUI-CADabra/main/assets/icon.png"
