"""
CADabra Nodes Module
Exports all node class mappings from different node modules
"""

# Import existing CAD nodes (Gmsh-based)
from .cad_nodes import (
    NODE_CLASS_MAPPINGS as CAD_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as CAD_NODE_DISPLAY_NAME_MAPPINGS
)

# Import new mesh reconstruction nodes
from .mesh_recon_nodes import (
    NODE_CLASS_MAPPINGS as MESH_RECON_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as MESH_RECON_NODE_DISPLAY_NAME_MAPPINGS
)

# Import CAD analysis nodes
from .cad_analysis_nodes import (
    NODE_CLASS_MAPPINGS as ANALYSIS_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as ANALYSIS_NODE_DISPLAY_NAME_MAPPINGS
)

# Import CAD edge analysis nodes (wireframe inspection)
from .cad_edge_analysis_nodes import (
    NODE_CLASS_MAPPINGS as EDGE_ANALYSIS_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as EDGE_ANALYSIS_NODE_DISPLAY_NAME_MAPPINGS
)

# Import Point2CAD nodes (CVPR 2024)
from .point2cad_nodes import (
    NODE_CLASS_MAPPINGS as POINT2CAD_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as POINT2CAD_NODE_DISPLAY_NAME_MAPPINGS
)

# Import new Point Cloud Loader Node
from .point_cloud_loader_node import (
    NODE_CLASS_MAPPINGS as POINT_CLOUD_LOADER_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as POINT_CLOUD_LOADER_NODE_DISPLAY_NAME_MAPPINGS
)

# Import CAD Utility nodes
from .cad_utility_nodes import (
    NODE_CLASS_MAPPINGS as CAD_UTILITY_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as CAD_UTILITY_NODE_DISPLAY_NAME_MAPPINGS
)

# Import CAD Face Projection nodes (2D projection for height maps)
from .cad_project_faces import (
    NODE_CLASS_MAPPINGS as CAD_PROJECT_FACES_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as CAD_PROJECT_FACES_NODE_DISPLAY_NAME_MAPPINGS
)

# Import BVH Raytracer node (requires occt_rt - optional dependency)
try:
    from .raytracer_node import (
        NODE_CLASS_MAPPINGS as RAYTRACER_NODE_CLASS_MAPPINGS,
        NODE_DISPLAY_NAME_MAPPINGS as RAYTRACER_NODE_DISPLAY_NAME_MAPPINGS
    )
except ImportError as e:
    print(f"[CADabra] Warning: Raytracer node not available: {e}")
    print("[CADabra] Install occt_rt to enable the CAD Raytracer (BVH) node.")
    RAYTRACER_NODE_CLASS_MAPPINGS = {}
    RAYTRACER_NODE_DISPLAY_NAME_MAPPINGS = {}

# Import ROI Selector node (interactive ROI selection)
from .cad_roi_selector_node import (
    NODE_CLASS_MAPPINGS as ROI_SELECTOR_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as ROI_SELECTOR_NODE_DISPLAY_NAME_MAPPINGS
)

# Import CAD-Recode nodes (ICCV 2025 - point cloud to CadQuery code)
from .cadrecode_nodes import (
    NODE_CLASS_MAPPINGS as CADRECODE_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as CADRECODE_NODE_DISPLAY_NAME_MAPPINGS
)

# Import Cadrille nodes (multi-modal CAD reconstruction)
from .cadrille_nodes import (
    NODE_CLASS_MAPPINGS as CADRILLE_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as CADRILLE_NODE_DISPLAY_NAME_MAPPINGS
)

# Import SECAD-Net nodes (sketch-extrude CAD reconstruction from voxels)
from .secadnet_nodes import (
    NODE_CLASS_MAPPINGS as SECADNET_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as SECADNET_NODE_DISPLAY_NAME_MAPPINGS
)

# Import NeurCADRecon nodes (neural implicit CAD reconstruction with Morse loss - SIGGRAPH 2024)
from .neurcadrecon_nodes import (
    NODE_CLASS_MAPPINGS as NEURCADRECON_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as NEURCADRECON_NODE_DISPLAY_NAME_MAPPINGS
)

# Import BGPSeg nodes (boundary-guided primitive segmentation - IEEE TIP 2025)
from .bgpseg_nodes import (
    NODE_CLASS_MAPPINGS as BGPSEG_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as BGPSEG_NODE_DISPLAY_NAME_MAPPINGS
)

# Import Mask utility nodes (MaskAnalyzer, MaskNormalizer, MasksToRGB)
from .mask_utils import (
    NODE_CLASS_MAPPINGS as MASK_UTILS_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as MASK_UTILS_NODE_DISPLAY_NAME_MAPPINGS
)

# Import CAD Transform nodes (rotate/translate/scale)
from .cad_transform_nodes import (
    NODE_CLASS_MAPPINGS as CAD_TRANSFORM_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as CAD_TRANSFORM_NODE_DISPLAY_NAME_MAPPINGS
)

# Import CAD Hierarchy Tree node (topology visualization)
from .cad_hierarchy_node import (
    NODE_CLASS_MAPPINGS as CAD_HIERARCHY_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as CAD_HIERARCHY_NODE_DISPLAY_NAME_MAPPINGS
)

# Import CAD Spline Viewer node (B-spline/Bezier/NURBS visualization)
from .cad_spline_viewer_node import (
    NODE_CLASS_MAPPINGS as CAD_SPLINE_VIEWER_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as CAD_SPLINE_VIEWER_NODE_DISPLAY_NAME_MAPPINGS
)

# Import CAD Edge Viewer VTK node (VTK.js with Trackball interactor for free 3D rotation)
from .cad_edge_viewer_vtk_node import (
    NODE_CLASS_MAPPINGS as CAD_EDGE_VIEWER_VTK_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as CAD_EDGE_VIEWER_VTK_NODE_DISPLAY_NAME_MAPPINGS
)

# Import CAD Curve Plotter node (2D visualization of B-spline/Bezier curves)
from .cad_curve_plotter_node import (
    NODE_CLASS_MAPPINGS as CAD_CURVE_PLOTTER_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as CAD_CURVE_PLOTTER_NODE_DISPLAY_NAME_MAPPINGS
)

# Import CAD Curvature node (curvature computation from CAD geometry -> TRIMESH)
from .cad_curvature_viewer_node import (
    NODE_CLASS_MAPPINGS as CAD_CURVATURE_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as CAD_CURVATURE_NODE_DISPLAY_NAME_MAPPINGS
)

# Import CAD Primitive Reconstruction node (detect & replace B-splines with circles/lines)
from .cad_primitive_reconstruction_node import (
    NODE_CLASS_MAPPINGS as CAD_PRIMITIVE_RECON_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as CAD_PRIMITIVE_RECON_NODE_DISPLAY_NAME_MAPPINGS
)

# Import Point2CAD Wireframe node (extract faces with boundary wires)
from .point2cad_wireframe_node import (
    NODE_CLASS_MAPPINGS as POINT2CAD_WIREFRAME_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as POINT2CAD_WIREFRAME_NODE_DISPLAY_NAME_MAPPINGS
)

# Combine all node mappings
NODE_CLASS_MAPPINGS = {
    **CAD_NODE_CLASS_MAPPINGS,
    **MESH_RECON_NODE_CLASS_MAPPINGS,
    **ANALYSIS_NODE_CLASS_MAPPINGS,
    **EDGE_ANALYSIS_NODE_CLASS_MAPPINGS,
    **POINT2CAD_NODE_CLASS_MAPPINGS,
    **POINT_CLOUD_LOADER_NODE_CLASS_MAPPINGS,
    **CAD_UTILITY_NODE_CLASS_MAPPINGS,
    **CAD_PROJECT_FACES_NODE_CLASS_MAPPINGS,
    **RAYTRACER_NODE_CLASS_MAPPINGS,
    **ROI_SELECTOR_NODE_CLASS_MAPPINGS,
    **CADRECODE_NODE_CLASS_MAPPINGS,
    **CADRILLE_NODE_CLASS_MAPPINGS,
    **SECADNET_NODE_CLASS_MAPPINGS,
    **NEURCADRECON_NODE_CLASS_MAPPINGS,
    **BGPSEG_NODE_CLASS_MAPPINGS,
    **MASK_UTILS_NODE_CLASS_MAPPINGS,
    **CAD_TRANSFORM_NODE_CLASS_MAPPINGS,
    **CAD_HIERARCHY_NODE_CLASS_MAPPINGS,
    **CAD_SPLINE_VIEWER_NODE_CLASS_MAPPINGS,
    **CAD_EDGE_VIEWER_VTK_NODE_CLASS_MAPPINGS,
    **CAD_CURVE_PLOTTER_NODE_CLASS_MAPPINGS,
    **CAD_CURVATURE_NODE_CLASS_MAPPINGS,
    **CAD_PRIMITIVE_RECON_NODE_CLASS_MAPPINGS,
    **POINT2CAD_WIREFRAME_NODE_CLASS_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **CAD_NODE_DISPLAY_NAME_MAPPINGS,
    **MESH_RECON_NODE_DISPLAY_NAME_MAPPINGS,
    **ANALYSIS_NODE_DISPLAY_NAME_MAPPINGS,
    **EDGE_ANALYSIS_NODE_DISPLAY_NAME_MAPPINGS,
    **POINT2CAD_NODE_DISPLAY_NAME_MAPPINGS,
    **POINT_CLOUD_LOADER_NODE_DISPLAY_NAME_MAPPINGS,
    **CAD_UTILITY_NODE_DISPLAY_NAME_MAPPINGS,
    **CAD_PROJECT_FACES_NODE_DISPLAY_NAME_MAPPINGS,
    **RAYTRACER_NODE_DISPLAY_NAME_MAPPINGS,
    **ROI_SELECTOR_NODE_DISPLAY_NAME_MAPPINGS,
    **CADRECODE_NODE_DISPLAY_NAME_MAPPINGS,
    **CADRILLE_NODE_DISPLAY_NAME_MAPPINGS,
    **SECADNET_NODE_DISPLAY_NAME_MAPPINGS,
    **NEURCADRECON_NODE_DISPLAY_NAME_MAPPINGS,
    **BGPSEG_NODE_DISPLAY_NAME_MAPPINGS,
    **MASK_UTILS_NODE_DISPLAY_NAME_MAPPINGS,
    **CAD_TRANSFORM_NODE_DISPLAY_NAME_MAPPINGS,
    **CAD_HIERARCHY_NODE_DISPLAY_NAME_MAPPINGS,
    **CAD_SPLINE_VIEWER_NODE_DISPLAY_NAME_MAPPINGS,
    **CAD_EDGE_VIEWER_VTK_NODE_DISPLAY_NAME_MAPPINGS,
    **CAD_CURVE_PLOTTER_NODE_DISPLAY_NAME_MAPPINGS,
    **CAD_CURVATURE_NODE_DISPLAY_NAME_MAPPINGS,
    **CAD_PRIMITIVE_RECON_NODE_DISPLAY_NAME_MAPPINGS,
    **POINT2CAD_WIREFRAME_NODE_DISPLAY_NAME_MAPPINGS,
}

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']